// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cbkmap.h"

/////////////////////////////////////////////////////////////////////////////
// CCBKMap

IMPLEMENT_DYNCREATE(CCBKMap, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCBKMap properties

/////////////////////////////////////////////////////////////////////////////
// CCBKMap operations

void CCBKMap::LoadMapFile(LPCTSTR strkcdm, LPCTSTR strUDate)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strkcdm, strUDate);
}

void CCBKMap::PlayBackMap(LPCTSTR strzkzm, short ikscs, short idrcs)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strzkzm, ikscs, idrcs);
}

void CCBKMap::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
