#if !defined(AFX_CBKMAP_H__EFD1B6E9_DCC1_4871_86CD_9EF5AF4A9CC5__INCLUDED_)
#define AFX_CBKMAP_H__EFD1B6E9_DCC1_4871_86CD_9EF5AF4A9CC5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCBKMap wrapper class

class CCBKMap : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCBKMap)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd8809dc2, 0x92bb, 0x4f79, { 0x9e, 0xa3, 0x58, 0xd9, 0xa8, 0xef, 0x9, 0xe2 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void LoadMapFile(LPCTSTR strkcdm, LPCTSTR strUDate);
	void PlayBackMap(LPCTSTR strzkzm, short ikscs, short idrcs);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CBKMAP_H__EFD1B6E9_DCC1_4871_86CD_9EF5AF4A9CC5__INCLUDED_)
