#if !defined(AFX_CBKPLAYZWNDX_H__EF7E8C62_DEF0_404E_9C99_53C2E358D98F__INCLUDED_)
#define AFX_CBKPLAYZWNDX_H__EF7E8C62_DEF0_404E_9C99_53C2E358D98F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCBKPlayzWndX wrapper class

class CCBKPlayzWndX : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCBKPlayzWndX)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd3b921a4, 0xe5d7, 0x48f4, { 0x80, 0x83, 0xcf, 0xea, 0x6e, 0x2b, 0x64, 0x74 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL StopPlay();
	void SetMultiWnd(short nSplit);
	BOOL SetRealStreamID(LPCTSTR strKchp, LPCTSTR csCameraID);
	void ShowRgppDlg(LPCTSTR strKchp, LPCTSTR strStuName, LPCTSTR strStuZkzm, LPCTSTR strReturn);
	void SetDeviceInfo(LPCTSTR strIP, LPCTSTR strUser, LPCTSTR strPwd, short nPort, short nChannel, short nType);
	BOOL SetPlayBackByTime(LPCTSTR strSTime, LPCTSTR strETime);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CBKPLAYZWNDX_H__EF7E8C62_DEF0_404E_9C99_53C2E358D98F__INCLUDED_)
