// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cbkplayzwndx.h"

/////////////////////////////////////////////////////////////////////////////
// CCBKPlayzWndX

IMPLEMENT_DYNCREATE(CCBKPlayzWndX, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCBKPlayzWndX properties

/////////////////////////////////////////////////////////////////////////////
// CCBKPlayzWndX operations

BOOL CCBKPlayzWndX::StopPlay()
{
	BOOL result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CCBKPlayzWndX::SetMultiWnd(short nSplit)
{
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nSplit);
}

BOOL CCBKPlayzWndX::SetRealStreamID(LPCTSTR strKchp, LPCTSTR csCameraID)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strKchp, csCameraID);
	return result;
}

void CCBKPlayzWndX::ShowRgppDlg(LPCTSTR strKchp, LPCTSTR strStuName, LPCTSTR strStuZkzm, LPCTSTR strReturn)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strKchp, strStuName, strStuZkzm, strReturn);
}

void CCBKPlayzWndX::SetDeviceInfo(LPCTSTR strIP, LPCTSTR strUser, LPCTSTR strPwd, short nPort, short nChannel, short nType)
{
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strIP, strUser, strPwd, nPort, nChannel, nType);
}

BOOL CCBKPlayzWndX::SetPlayBackByTime(LPCTSTR strSTime, LPCTSTR strETime)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strSTime, strETime);
	return result;
}

void CCBKPlayzWndX::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
