// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "cplaybackzocx.h"

/////////////////////////////////////////////////////////////////////////////
// CCPlayBackzOcx

IMPLEMENT_DYNCREATE(CCPlayBackzOcx, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCPlayBackzOcx properties

/////////////////////////////////////////////////////////////////////////////
// CCPlayBackzOcx operations

BOOL CCPlayBackzOcx::LoginDevice(LPCTSTR strIP, LPCTSTR strUser, LPCTSTR strPwd, short nPort, short nChannel)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR VTS_BSTR VTS_I2 VTS_I2;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strIP, strUser, strPwd, nPort, nChannel);
	return result;
}

BOOL CCPlayBackzOcx::SetPlayBackByTime(LPCTSTR strSTime, LPCTSTR strETime)
{
	BOOL result;
	static BYTE parms[] =
		VTS_BSTR VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BOOL, (void*)&result, parms,
		strSTime, strETime);
	return result;
}

void CCPlayBackzOcx::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
